ChouettesBundle\Entity\Newsletter:
    type: entity
    table: null
    repositoryClass: ChouettesBundle\Repository\NewsletterRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        email:
            type: string
            length: 255
        token:
            type: string
            length: 255
    lifecycleCallbacks: {  }
