imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@ChouettesBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    http_protocol: http
    fb_app_id: "%facebook_app_id%"
    fb_app_secret: "%facebook_app_secret%"
    fb_page_id: "%facebook_page_id%"
    fb_token: "%facebook_token%"

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enabled: true, enable_annotations: false }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    encryption: ssl
    spool:     { type: memory }

# Tinymce Configuration
stfalcon_tinymce:
    selector: ".tinymce"
    language: %locale%

    theme:
        ## Simple theme: same as default theme
        simple:
            theme: "modern"
            toolbar1: "insertfile undo redo  | bold italic underline | bullist numlist outdent indent removeformat | link image"

# FOSUser Configuration
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: ChouettesBundle\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"
#lexik maintenance configuration
lexik_maintenance:
    authorized:
#        path: /                                                                    # Optional. Authorized path, accepts regexs
        ips: ['78.205.106.82', '82.251.11.246', '176.134.90.40', '193.251.63.39']

        # 1 ==> Anthony / 2 ==> Sophie / 3 ==> Florian home / 4 ==> wvc
    driver:

         # File driver
        class: '\Lexik\Bundle\MaintenanceBundle\Drivers\FileDriver'                # class for file driver
        options: {file_path: %kernel.root_dir%/cache/lock}                         # file_path is the complete path for create the file

         # Shared memory driver
        class: '\Lexik\Bundle\MaintenanceBundle\Drivers\ShmDriver'                 # class for shared memory driver

         # MemCache driver
        class: Lexik\Bundle\MaintenanceBundle\Drivers\MemCacheDriver               # class for MemCache driver
        options: {key_name: 'maintenance', host: 127.0.0.1, port: 11211}           # need to define a key_name, the host and port

        # Database driver:
        class: 'Lexik\Bundle\MaintenanceBundle\Drivers\DatabaseDriver'             # class for database driver

        # Option 1 : for doctrine
        options: {connection: custom}                                              # Optional. You can choice an other connection. Without option it's the doctrine default connection who will be used


    #Optional. response code and status of the maintenance page
    response:
        code: 503
        status: "Service Temporarily Unavailable"

#KnpPaginatorBundle
knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: ChouettesBundle:user:pagination.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

liip_imagine:
    resolvers:
        default:
            web_path: ~
    loaders:
        default:
            filesystem:
                data_root:
                    - "%kernel.root_dir%/../web/uploads/images/"
                    - "%kernel.root_dir%/../web/bundles/chouettes/images/"
    filter_sets:
        cache: ~
        my_thumb:
            quality: 75
            filters:
                thumbnail: { size: [250, 250], mode: outbound }
        thumb_fixe:
            quality: 75
            filters:
                relative_resize: { widen: 336 }
        newsletter:
            quality: 80
            filters:
                relative_resize: { widen: 500 }