<?php

namespace ChouettesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * WhoamiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WhoamiRepository extends EntityRepository
{
    /**
     * Get profil and picture
     * @return mixed
     */
    public function getProfilInfo(){
        $qb = $this->createQueryBuilder('w');
        $qb->select('w.text as text')
            ->join('w.image', 'i')
            ->addSelect('i.url as image', 'i.alt as alt');
        return $qb->getQuery()->getSingleResult();
    }
}
